#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
import json
import math
import re
import sys
from collections import defaultdict
from dataclasses import asdict
from pathlib import Path
from typing import Any

import torch
from torch.utils.data import DataLoader

REPO_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = REPO_ROOT / "src"

sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(SRC_ROOT))

from PitchExtraction_v1 import PitchExtractionBatchConverter
from PitchExtraction_v1.nanopitch_runtime import NanoPitchRuntimeConfig
from voice_coach.data.collator import VoiceCoachRawBatchCollator
from voice_coach.data.manifest import Recording, save_manifest
from voice_coach.data.runtime_dataset import VoiceCoachRuntimeDataset


DEFAULT_DATASET_ROOT = Path("/mnt/archive/GTSinger/English/EN-Alto-1")
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent / "outputs"
CONTROL_GROUP = "Control_Group"


def main() -> None:
    parser = argparse.ArgumentParser(description="Run PitchExtraction_v1 on GTSinger Control_Group recordings only.")
    parser.add_argument("--dataset-root", type=Path, default=DEFAULT_DATASET_ROOT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--weights", type=Path, default=REPO_ROOT / "PitchExtraction_v1" / "weights.pth")
    parser.add_argument("--limit", type=int, default=4)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--decoder", choices=["argmax", "offline", "realtime"], default="argmax")
    parser.add_argument("--selection", choices=["round_robin", "first"], default="round_robin")
    parser.add_argument("--save-predictions", action="store_true")
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    recordings = discover_gtsinger_triplets(
        args.dataset_root,
        limit=args.limit,
        selection=args.selection,
    )
    if not recordings:
        raise RuntimeError(f"No WAV/MusicXML triplets found under {args.dataset_root}")

    manifest_path = args.output_dir / "manifest.json"
    save_manifest(recordings, manifest_path)

    dataset = VoiceCoachRuntimeDataset(recordings=recordings, cache_references=True)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=args.device.startswith("cuda"),
        collate_fn=VoiceCoachRawBatchCollator(),
    )
    converter = PitchExtractionBatchConverter(
        nanopitch_config=NanoPitchRuntimeConfig(weights_path=args.weights, decoder=args.decoder),
        device=args.device,
        use_amp_features=args.device.startswith("cuda"),
    )

    rows: list[dict[str, Any]] = []
    all_cents: list[torch.Tensor] = []
    prediction_dir = args.output_dir / "predictions"
    if args.save_predictions:
        prediction_dir.mkdir(parents=True, exist_ok=True)

    for raw_batch in loader:
        batch = converter(raw_batch)
        rows.extend(batch_rows(batch))
        cents = batch_cents(batch)
        if cents.numel() > 0:
            all_cents.append(cents.cpu())

        if args.save_predictions:
            write_prediction_csvs(batch, prediction_dir)

    summary = {
        "dataset_root": str(args.dataset_root),
        "weights": str(args.weights),
        "device": args.device,
        "decoder": args.decoder,
        "num_recordings": len(recordings),
        "batch_size": args.batch_size,
        "group": CONTROL_GROUP,
        "selection": args.selection,
        "manifest_path": str(manifest_path),
        "recordings": rows,
        "aggregate_pitch_metrics": aggregate_pitch_metrics(all_cents),
        "notes": [
            "Reference f0 is generated by the runtime label builder; GTSinger JSON note timings are preferred when present.",
            "Pitch metrics compare NanoPitch on its native frame grid against reference labels sampled at NanoPitch times.",
            "This is a smoke/integration test, not a final benchmark.",
        ],
    }
    summary_path = args.output_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2))

    print(f"manifest: {manifest_path}")
    print(f"summary: {summary_path}")
    print(json.dumps(summary["aggregate_pitch_metrics"], indent=2))


def discover_gtsinger_triplets(
    dataset_root: Path,
    limit: int | None,
    selection: str = "round_robin",
) -> list[Recording]:
    wavs = sorted(dataset_root.rglob("*.wav"))
    candidates: list[Recording] = []

    for wav_path in wavs:
        if wav_path.parent.name != CONTROL_GROUP:
            continue
        musicxml_path = wav_path.with_suffix(".musicxml")
        if not musicxml_path.exists():
            musicxml_path = wav_path.with_suffix(".xml")
        if not musicxml_path.exists():
            continue

        textgrid_path = wav_path.with_suffix(".TextGrid")
        if not textgrid_path.exists():
            textgrid_path = wav_path.with_suffix(".textgrid")

        relative = wav_path.relative_to(dataset_root).with_suffix("")
        recording_id = sanitize_recording_id(str(relative))
        song_id = sanitize_recording_id(str(relative.parent)) if relative.parent != Path(".") else wav_path.stem
        candidates.append(
            Recording(
                recording_id=recording_id,
                song_id=song_id,
                wav_path=wav_path,
                musicxml_path=musicxml_path,
                textgrid_path=textgrid_path if textgrid_path.exists() else None,
            )
        )

    if selection == "first":
        return candidates[:limit] if limit is not None else candidates
    if selection == "round_robin":
        return round_robin_by_technique(candidates, dataset_root, limit)
    raise ValueError(f"Unsupported selection mode: {selection}")


def round_robin_by_technique(
    recordings: list[Recording],
    dataset_root: Path,
    limit: int | None,
) -> list[Recording]:
    grouped: dict[str, list[Recording]] = defaultdict(list)
    for recording in recordings:
        relative = recording.wav_path.relative_to(dataset_root)
        technique = relative.parts[0] if relative.parts else "unknown"
        grouped[technique].append(recording)

    selected: list[Recording] = []
    techniques = sorted(grouped)
    index = 0
    while True:
        added = False
        for technique in techniques:
            items = grouped[technique]
            if index < len(items):
                selected.append(items[index])
                added = True
                if limit is not None and len(selected) >= limit:
                    return selected
        if not added:
            return selected
        index += 1



def batch_rows(batch: dict[str, Any]) -> list[dict[str, Any]]:
    rows = []
    labels = batch["labels"]
    nanopitch = batch["nanopitch"]
    metadata = batch["metadata"]

    for index, item in enumerate(metadata):
        native_voiced = nanopitch["voiced"][index] > 0.5
        native_f0 = nanopitch["f0_hz"][index]
        ref_voiced = labels["nanopitch_ref_voicing"][index] > 0.5
        ref_f0 = labels["nanopitch_ref_f0"][index]
        valid = torch.arange(native_f0.numel(), device=native_f0.device) < nanopitch["frame_lengths"][index]
        both = valid & ref_voiced & native_voiced & (ref_f0 > 0) & (native_f0 > 0)
        cents = cents_error(native_f0[both], ref_f0[both])
        native_positive = native_f0[native_voiced & (native_f0 > 0)]

        rows.append(
            {
                "recording_id": item["recording_id"],
                "song_id": item["song_id"],
                "wav_path": item["wav_path"],
                "main_frames": int(labels["f0"].shape[1]),
                "nanopitch_frames": int(nanopitch["f0_hz"].shape[1]),
                "reference_voiced_frames": int(ref_voiced[valid].sum().item()),
                "nanopitch_voiced_frames_aligned": int((labels["nanopitch_voicing"][index] > 0.5).sum().item()),
                "nanopitch_voiced_frames_native": int(native_voiced.sum().item()),
                "nanopitch_f0_min_hz": float(native_positive.min().item()) if native_positive.numel() else 0.0,
                "nanopitch_f0_max_hz": float(native_positive.max().item()) if native_positive.numel() else 0.0,
                "pitch_acc_50": float((cents.abs() <= 50.0).float().mean().item()) if cents.numel() else None,
                "mace_cents": float(cents.abs().mean().item()) if cents.numel() else None,
                "pitch_rmse_cents": float(torch.sqrt((cents.square()).mean()).item()) if cents.numel() else None,
                "comparison_frames": int(cents.numel()),
            }
        )

    return rows


def batch_cents(batch: dict[str, Any]) -> torch.Tensor:
    labels = batch["labels"]
    nanopitch = batch["nanopitch"]
    both = (
        (labels["nanopitch_ref_voicing"] > 0.5)
        & (nanopitch["voiced"] > 0.5)
        & (labels["nanopitch_ref_f0"] > 0)
        & (nanopitch["f0_hz"] > 0)
        & nanopitch["attention_mask"]
    )
    if not both.any():
        return torch.empty(0)
    return cents_error(nanopitch["f0_hz"][both], labels["nanopitch_ref_f0"][both])


def aggregate_pitch_metrics(cents_parts: list[torch.Tensor]) -> dict[str, Any]:
    if not cents_parts:
        return {
            "comparison_frames": 0,
            "pitch_acc_50": None,
            "mace_cents": None,
            "pitch_rmse_cents": None,
        }
    cents = torch.cat(cents_parts)
    return {
        "comparison_frames": int(cents.numel()),
        "pitch_acc_50": float((cents.abs() <= 50.0).float().mean().item()),
        "mace_cents": float(cents.abs().mean().item()),
        "pitch_rmse_cents": float(torch.sqrt(cents.square().mean()).item()),
    }


def cents_error(pred_f0: torch.Tensor, ref_f0: torch.Tensor) -> torch.Tensor:
    return 1200.0 * torch.log2(torch.clamp(pred_f0, min=1e-6) / torch.clamp(ref_f0, min=1e-6))


def write_prediction_csvs(batch: dict[str, Any], prediction_dir: Path) -> None:
    nanopitch = batch["nanopitch"]
    times = nanopitch["times"].detach().cpu().tolist()
    for index, item in enumerate(batch["metadata"]):
        output_path = prediction_dir / f"{item['recording_id']}_nanopitch.csv"
        f0 = nanopitch["f0_hz"][index].detach().cpu().tolist()
        voiced = nanopitch["voiced"][index].detach().cpu().tolist()
        vad = nanopitch["vad_prob"][index].detach().cpu().tolist()
        confidence = nanopitch["pitch_confidence"][index].detach().cpu().tolist()
        with output_path.open("w", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(["time_sec", "f0_hz", "voiced", "vad_prob", "pitch_confidence"])
            for row in zip(times, f0, voiced, vad, confidence, strict=True):
                writer.writerow(row)


def sanitize_recording_id(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")


if __name__ == "__main__":
    main()
