#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import torch
from torch.utils.data import DataLoader

REPO_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = REPO_ROOT / "src"

sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(SRC_ROOT))

from PitchExtraction_RMVPE_v1 import RMVPEBatchConverter, RMVPERuntimeConfig
from hf_models.data.collator import VoiceCoachRawBatchCollator
from hf_models.data.manifest import Recording, save_manifest
from hf_models.data.runtime_dataset import VoiceCoachRuntimeDataset


DEFAULT_DATASET_ROOT = Path("/mnt/archive/GTSinger/English/EN-Alto-1")
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent / "outputs"
CONTROL_GROUP = "Control_Group"


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate RMVPE on GTSinger Control_Group recordings.")
    parser.add_argument("--dataset-root", type=Path, default=DEFAULT_DATASET_ROOT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--model-path", type=Path, default=None)
    parser.add_argument("--limit", type=int, default=4)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--confidence-threshold", type=float, default=0.35)
    parser.add_argument("--providers", nargs="*", default=None)
    parser.add_argument("--selection", choices=["round_robin", "first"], default="round_robin")
    parser.add_argument("--save-predictions", action="store_true")
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    prediction_dir = args.output_dir / "predictions"
    if args.save_predictions:
        prediction_dir.mkdir(parents=True, exist_ok=True)

    recordings = discover_control_group_triplets(args.dataset_root, args.limit, args.selection)
    if not recordings:
        raise RuntimeError(f"No Control_Group WAV/MusicXML triplets found under {args.dataset_root}")

    manifest_path = args.output_dir / "manifest.json"
    save_manifest(recordings, manifest_path)

    dataset = VoiceCoachRuntimeDataset(recordings=recordings, cache_references=True)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=args.device.startswith("cuda"),
        collate_fn=VoiceCoachRawBatchCollator(),
    )
    converter = RMVPEBatchConverter(
        rmvpe_config=RMVPERuntimeConfig(
            model_path=args.model_path,
            confidence_threshold=args.confidence_threshold,
            providers=tuple(args.providers) if args.providers else None,
        ),
        device=args.device,
        use_amp_features=args.device.startswith("cuda"),
    )

    rows: list[dict[str, Any]] = []
    cents_parts: list[torch.Tensor] = []
    for raw_batch in loader:
        batch = converter(raw_batch)
        rows.extend(batch_rows(batch))
        cents = batch_cents(batch)
        if cents.numel() > 0:
            cents_parts.append(cents.cpu())
        if args.save_predictions:
            write_prediction_csvs(batch, prediction_dir)

    summary = {
        "dataset_root": str(args.dataset_root),
        "model_path": str(args.model_path) if args.model_path else None,
        "device": args.device,
        "providers": args.providers,
        "confidence_threshold": args.confidence_threshold,
        "group": CONTROL_GROUP,
        "selection": args.selection,
        "num_recordings": len(recordings),
        "manifest_path": str(manifest_path),
        "recordings": rows,
        "aggregate_pitch_metrics": aggregate_pitch_metrics(cents_parts),
        "notes": [
            "Reference f0 is generated by the runtime label builder; GTSinger JSON note timings are preferred when present.",
            "Pitch metrics compare RMVPE on its returned frame grid against reference labels sampled at RMVPE times.",
            "RMVPE is loaded through rmvpe-onnx and may download the HF ONNX model on first use.",
        ],
    }
    summary_path = args.output_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2))
    print(f"manifest: {manifest_path}")
    print(f"summary: {summary_path}")
    print(json.dumps(summary["aggregate_pitch_metrics"], indent=2))


def batch_rows(batch: dict[str, Any]) -> list[dict[str, Any]]:
    rows = []
    labels = batch["labels"]
    rmvpe = batch["rmvpe"]

    for index, metadata in enumerate(batch["metadata"]):
        f0 = rmvpe["f0_hz"][index]
        voiced = rmvpe["voiced"][index] > 0.5
        ref_f0 = labels["rmvpe_ref_f0"][index]
        ref_voiced = labels["rmvpe_ref_voicing"][index] > 0.5
        valid = rmvpe["attention_mask"][index]
        both = valid & voiced & ref_voiced & (f0 > 0) & (ref_f0 > 0)
        cents = cents_error(f0[both], ref_f0[both])
        positive = f0[valid & voiced & (f0 > 0)]

        rows.append(
            {
                "recording_id": metadata["recording_id"],
                "song_id": metadata["song_id"],
                "wav_path": metadata["wav_path"],
                "rmvpe_frames": int(rmvpe["frame_lengths"][index].item()),
                "reference_voiced_frames": int((valid & ref_voiced).sum().item()),
                "rmvpe_voiced_frames": int((valid & voiced).sum().item()),
                "rmvpe_f0_min_hz": float(positive.min().item()) if positive.numel() else 0.0,
                "rmvpe_f0_max_hz": float(positive.max().item()) if positive.numel() else 0.0,
                "pitch_acc_50": float((cents.abs() <= 50.0).float().mean().item()) if cents.numel() else None,
                "pitch_acc_100": float((cents.abs() <= 100.0).float().mean().item()) if cents.numel() else None,
                "mace_cents": float(cents.abs().mean().item()) if cents.numel() else None,
                "median_abs_cents": float(cents.abs().median().item()) if cents.numel() else None,
                "pitch_rmse_cents": float(torch.sqrt(cents.square().mean()).item()) if cents.numel() else None,
                "raw_chroma_acc_50": raw_chroma_acc_50(cents),
                "octave_error_rate": octave_error_rate(cents),
                "comparison_frames": int(cents.numel()),
            }
        )
    return rows


def batch_cents(batch: dict[str, Any]) -> torch.Tensor:
    labels = batch["labels"]
    rmvpe = batch["rmvpe"]
    both = (
        rmvpe["attention_mask"]
        & (rmvpe["voiced"] > 0.5)
        & (labels["rmvpe_ref_voicing"] > 0.5)
        & (rmvpe["f0_hz"] > 0)
        & (labels["rmvpe_ref_f0"] > 0)
    )
    if not both.any():
        return torch.empty(0)
    return cents_error(rmvpe["f0_hz"][both], labels["rmvpe_ref_f0"][both])


def aggregate_pitch_metrics(cents_parts: list[torch.Tensor]) -> dict[str, Any]:
    if not cents_parts:
        return {
            "comparison_frames": 0,
            "pitch_acc_50": None,
            "mace_cents": None,
            "pitch_rmse_cents": None,
        }
    cents = torch.cat(cents_parts)
    return {
        "comparison_frames": int(cents.numel()),
        "pitch_acc_50": float((cents.abs() <= 50.0).float().mean().item()),
        "pitch_acc_100": float((cents.abs() <= 100.0).float().mean().item()),
        "mace_cents": float(cents.abs().mean().item()),
        "median_abs_cents": float(cents.abs().median().item()),
        "pitch_rmse_cents": float(torch.sqrt(cents.square().mean()).item()),
        "raw_chroma_acc_50": raw_chroma_acc_50(cents),
        "octave_error_rate": octave_error_rate(cents),
    }


def cents_error(pred_f0: torch.Tensor, ref_f0: torch.Tensor) -> torch.Tensor:
    return 1200.0 * torch.log2(torch.clamp(pred_f0, min=1e-6) / torch.clamp(ref_f0, min=1e-6))


def raw_chroma_acc_50(cents: torch.Tensor) -> float | None:
    if cents.numel() == 0:
        return None
    abs_cents = cents.abs()
    chroma = torch.remainder(abs_cents, 1200.0)
    chroma = torch.minimum(chroma, 1200.0 - chroma)
    return float((chroma <= 50.0).float().mean().item())


def octave_error_rate(cents: torch.Tensor) -> float | None:
    if cents.numel() == 0:
        return None
    abs_cents = cents.abs()
    chroma = torch.remainder(abs_cents, 1200.0)
    chroma = torch.minimum(chroma, 1200.0 - chroma)
    return float(((abs_cents > 600.0) & (chroma <= 50.0)).float().mean().item())


def write_prediction_csvs(batch: dict[str, Any], prediction_dir: Path) -> None:
    rmvpe = batch["rmvpe"]
    labels = batch["labels"]
    for index, metadata in enumerate(batch["metadata"]):
        output_path = prediction_dir / f"{metadata['recording_id']}_rmvpe.csv"
        length = int(rmvpe["frame_lengths"][index].item())
        rows = zip(
            rmvpe["times"][index, :length].detach().cpu().tolist(),
            rmvpe["f0_hz"][index, :length].detach().cpu().tolist(),
            rmvpe["voiced"][index, :length].detach().cpu().tolist(),
            rmvpe["confidence"][index, :length].detach().cpu().tolist(),
            labels["rmvpe_ref_f0"][index, :length].detach().cpu().tolist(),
            labels["rmvpe_ref_voicing"][index, :length].detach().cpu().tolist(),
            strict=True,
        )
        with output_path.open("w", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(["time_sec", "rmvpe_f0_hz", "rmvpe_voiced", "confidence", "reference_f0_hz", "reference_voiced"])
            writer.writerows(rows)


def discover_control_group_triplets(
    dataset_root: Path,
    limit: int | None,
    selection: str,
) -> list[Recording]:
    candidates: list[Recording] = []
    for wav_path in sorted(dataset_root.rglob("*.wav")):
        if wav_path.parent.name != CONTROL_GROUP:
            continue
        musicxml_path = wav_path.with_suffix(".musicxml")
        if not musicxml_path.exists():
            musicxml_path = wav_path.with_suffix(".xml")
        if not musicxml_path.exists():
            continue
        textgrid_path = wav_path.with_suffix(".TextGrid")
        if not textgrid_path.exists():
            textgrid_path = wav_path.with_suffix(".textgrid")
        relative = wav_path.relative_to(dataset_root).with_suffix("")
        candidates.append(
            Recording(
                recording_id=sanitize_recording_id(str(relative)),
                song_id=sanitize_recording_id(str(relative.parent)),
                wav_path=wav_path,
                musicxml_path=musicxml_path,
                textgrid_path=textgrid_path if textgrid_path.exists() else None,
            )
        )

    if selection == "first":
        return candidates[:limit] if limit is not None else candidates
    if selection == "round_robin":
        return round_robin_by_technique(candidates, dataset_root, limit)
    raise ValueError(f"Unsupported selection mode: {selection}")


def round_robin_by_technique(recordings: list[Recording], dataset_root: Path, limit: int | None) -> list[Recording]:
    grouped: dict[str, list[Recording]] = defaultdict(list)
    for recording in recordings:
        relative = recording.wav_path.relative_to(dataset_root)
        technique = relative.parts[0] if relative.parts else "unknown"
        grouped[technique].append(recording)
    selected: list[Recording] = []
    techniques = sorted(grouped)
    index = 0
    while True:
        added = False
        for technique in techniques:
            items = grouped[technique]
            if index < len(items):
                selected.append(items[index])
                added = True
                if limit is not None and len(selected) >= limit:
                    return selected
        if not added:
            return selected
        index += 1


def sanitize_recording_id(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")


if __name__ == "__main__":
    main()
